### ISSUE TITLE
Relax pyyaml version constraints

### ISSUE THREAD

**Issue by arwedus** [jackdewinter/application_properties#216]
Currently, we have a pinned version dependency to the locally installed ubuntu version of pyyaml in our docker images, since otherwise pip complains about uninstall and also c-bindings won't be available so that performance is low.

At least that is what I was told by our CI/CD engineers.

Unfortunately, since we do not install or run pymarkdownlnt in an isolated virtual environment, this means we cannot upgrade to the most recent pymarkdownlnt version. Would it be possible to support versions of pyyaml from 5.4.1 to 6.x?

**Comment by jackdewinter** [comment]
Have been doing bug fixes for the last month.  Will look into this before the next release in a couple of days.  Is it fair to say "5.4 to 6.0" is sufficient?

**Comment by arwedus** [comment]
Thank you! Yes that would work

**Comment by arwedus** [comment]
@jackdewinter: I tried to use the newest pymarkdownlnt release, but it still requires application-properties 0.8.1, which still requires PyYaml >= 6.0. Should I try out locally with relaxed constraints in application-properties?

**Comment by arwedus** [comment]
Hi @jackdewinter, I just tried out with the following requirements.txt installed in a virtualenv and pymarkdownlint worked:

```
application_properties==0.8.2
pymarkdownlnt==0.9.16
pyyaml==5.4.1.post0  # constraint
```

lgtm after all? :-)
